#!/bin/sh
cat > /usr/share/nginx/html/env-config.js << EOF
window.__env__ = {
  AT_FRONTEND_URL: "${PLATFORM_PROTOCOL}://${PLATFORM_HOST}${TRACKER_PATH}",
  N8N_URL: "${PLATFORM_PROTOCOL}://${PLATFORM_HOST}${N8N_PATH}",
  ADMINER_URL: "${PLATFORM_PROTOCOL}://${PLATFORM_HOST}${ADMINER_PATH}",
  TRAEFIK_URL: "${PLATFORM_PROTOCOL}://${PLATFORM_HOST}${TRAEFIK_PATH}",
  HEALTHCHECK_URL: "${PLATFORM_PROTOCOL}://${PLATFORM_HOST}${SERVICES_HEALTH_PATH}"
};
EOF
exec "$@"
  